// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/post.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	IsPublished   bool                   `protobuf:"varint,3,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	TopicId       string                 `protobuf:"bytes,4,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Images        []*CreateImageRequest  `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_proto_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostRequest) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *CreatePostRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *CreatePostRequest) GetImages() []*CreateImageRequest {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreatePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base64Data    string                 `protobuf:"bytes,1,opt,name=base64_data,json=base64Data,proto3" json:"base64_data,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	IsThumbnail   bool                   `protobuf:"varint,3,opt,name=is_thumbnail,json=isThumbnail,proto3" json:"is_thumbnail,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateImageRequest) Reset() {
	*x = CreateImageRequest{}
	mi := &file_proto_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImageRequest) ProtoMessage() {}

func (x *CreateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImageRequest.ProtoReflect.Descriptor instead.
func (*CreateImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{1}
}

func (x *CreateImageRequest) GetBase64Data() string {
	if x != nil {
		return x.Base64Data
	}
	return ""
}

func (x *CreateImageRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CreateImageRequest) GetIsThumbnail() bool {
	if x != nil {
		return x.IsThumbnail
	}
	return false
}

func (x *CreateImageRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type RestoreManyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreManyRequest) Reset() {
	*x = RestoreManyRequest{}
	mi := &file_proto_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreManyRequest) ProtoMessage() {}

func (x *RestoreManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreManyRequest.ProtoReflect.Descriptor instead.
func (*RestoreManyRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{2}
}

func (x *RestoreManyRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *RestoreManyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RestoredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoredResponse) Reset() {
	*x = RestoredResponse{}
	mi := &file_proto_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoredResponse) ProtoMessage() {}

func (x *RestoredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoredResponse.ProtoReflect.Descriptor instead.
func (*RestoredResponse) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{3}
}

func (x *RestoredResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RestoreOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreOneRequest) Reset() {
	*x = RestoreOneRequest{}
	mi := &file_proto_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreOneRequest) ProtoMessage() {}

func (x *RestoreOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreOneRequest.ProtoReflect.Descriptor instead.
func (*RestoreOneRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreOneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RestoreOneRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PermanentlyDeleteManyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermanentlyDeleteManyRequest) Reset() {
	*x = PermanentlyDeleteManyRequest{}
	mi := &file_proto_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermanentlyDeleteManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermanentlyDeleteManyRequest) ProtoMessage() {}

func (x *PermanentlyDeleteManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermanentlyDeleteManyRequest.ProtoReflect.Descriptor instead.
func (*PermanentlyDeleteManyRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{5}
}

func (x *PermanentlyDeleteManyRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type PermanentlyDeleteOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermanentlyDeleteOneRequest) Reset() {
	*x = PermanentlyDeleteOneRequest{}
	mi := &file_proto_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermanentlyDeleteOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermanentlyDeleteOneRequest) ProtoMessage() {}

func (x *PermanentlyDeleteOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermanentlyDeleteOneRequest.ProtoReflect.Descriptor instead.
func (*PermanentlyDeleteOneRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{6}
}

func (x *PermanentlyDeleteOneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteManyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManyRequest) Reset() {
	*x = DeleteManyRequest{}
	mi := &file_proto_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManyRequest) ProtoMessage() {}

func (x *DeleteManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManyRequest.ProtoReflect.Descriptor instead.
func (*DeleteManyRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteManyRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DeleteManyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOneRequest) Reset() {
	*x = DeleteOneRequest{}
	mi := &file_proto_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOneRequest) ProtoMessage() {}

func (x *DeleteOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOneRequest.ProtoReflect.Descriptor instead.
func (*DeleteOneRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteOneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteOneRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletedResponse) Reset() {
	*x = DeletedResponse{}
	mi := &file_proto_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedResponse) ProtoMessage() {}

func (x *DeletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedResponse.ProtoReflect.Descriptor instead.
func (*DeletedResponse) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{9}
}

func (x *DeletedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatedResponse) Reset() {
	*x = UpdatedResponse{}
	mi := &file_proto_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedResponse) ProtoMessage() {}

func (x *UpdatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedResponse.ProtoReflect.Descriptor instead.
func (*UpdatedResponse) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicRequest) Reset() {
	*x = UpdateTopicRequest{}
	mi := &file_proto_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicRequest) ProtoMessage() {}

func (x *UpdateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicRequest.ProtoReflect.Descriptor instead.
func (*UpdateTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTopicRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTopicRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateTopicRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TopicsAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*TopicAdminResponse  `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicsAdminResponse) Reset() {
	*x = TopicsAdminResponse{}
	mi := &file_proto_post_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicsAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicsAdminResponse) ProtoMessage() {}

func (x *TopicsAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicsAdminResponse.ProtoReflect.Descriptor instead.
func (*TopicsAdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{12}
}

func (x *TopicsAdminResponse) GetTopics() []*TopicAdminResponse {
	if x != nil {
		return x.Topics
	}
	return nil
}

type TopicAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy     *BaseUserResponse      `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     *BaseUserResponse      `protobuf:"bytes,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicAdminResponse) Reset() {
	*x = TopicAdminResponse{}
	mi := &file_proto_post_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicAdminResponse) ProtoMessage() {}

func (x *TopicAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicAdminResponse.ProtoReflect.Descriptor instead.
func (*TopicAdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{13}
}

func (x *TopicAdminResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TopicAdminResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicAdminResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *TopicAdminResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TopicAdminResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *TopicAdminResponse) GetCreatedBy() *BaseUserResponse {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *TopicAdminResponse) GetUpdatedBy() *BaseUserResponse {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

type BaseUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Profile       *BaseProfileResponse   `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseUserResponse) Reset() {
	*x = BaseUserResponse{}
	mi := &file_proto_post_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseUserResponse) ProtoMessage() {}

func (x *BaseUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseUserResponse.ProtoReflect.Descriptor instead.
func (*BaseUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{14}
}

func (x *BaseUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BaseUserResponse) GetProfile() *BaseProfileResponse {
	if x != nil {
		return x.Profile
	}
	return nil
}

type BaseProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseProfileResponse) Reset() {
	*x = BaseProfileResponse{}
	mi := &file_proto_post_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseProfileResponse) ProtoMessage() {}

func (x *BaseProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseProfileResponse.ProtoReflect.Descriptor instead.
func (*BaseProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{15}
}

func (x *BaseProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseProfileResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *BaseProfileResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type GetManyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManyRequest) Reset() {
	*x = GetManyRequest{}
	mi := &file_proto_post_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManyRequest) ProtoMessage() {}

func (x *GetManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManyRequest.ProtoReflect.Descriptor instead.
func (*GetManyRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{16}
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          *string                `protobuf:"bytes,2,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_proto_post_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{17}
}

func (x *CreateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTopicRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *CreateTopicRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedResponse) Reset() {
	*x = CreatedResponse{}
	mi := &file_proto_post_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedResponse) ProtoMessage() {}

func (x *CreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedResponse.ProtoReflect.Descriptor instead.
func (*CreatedResponse) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{18}
}

func (x *CreatedResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_post_proto protoreflect.FileDescriptor

const file_proto_post_proto_rawDesc = "" +
	"\n" +
	"\x10proto/post.proto\x12\x04post\"\xcc\x01\n" +
	"\x11CreatePostRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12!\n" +
	"\fis_published\x18\x03 \x01(\bR\visPublished\x12\x19\n" +
	"\btopic_id\x18\x04 \x01(\tR\atopicId\x120\n" +
	"\x06images\x18\x05 \x03(\v2\x18.post.CreateImageRequestR\x06images\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\"\x94\x01\n" +
	"\x12CreateImageRequest\x12\x1f\n" +
	"\vbase64_data\x18\x01 \x01(\tR\n" +
	"base64Data\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\fis_thumbnail\x18\x03 \x01(\bR\visThumbnail\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\"?\n" +
	"\x12RestoreManyRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\",\n" +
	"\x10RestoredResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"<\n" +
	"\x11RestoreOneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"0\n" +
	"\x1cPermanentlyDeleteManyRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"-\n" +
	"\x1bPermanentlyDeleteOneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x11DeleteManyRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\";\n" +
	"\x10DeleteOneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"+\n" +
	"\x0fDeletedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x0fUpdatedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"e\n" +
	"\x12UpdateTopicRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"G\n" +
	"\x13TopicsAdminResponse\x120\n" +
	"\x06topics\x18\x01 \x03(\v2\x18.post.TopicAdminResponseR\x06topics\"\xf8\x01\n" +
	"\x12TopicAdminResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x125\n" +
	"\n" +
	"created_by\x18\x06 \x01(\v2\x16.post.BaseUserResponseR\tcreatedBy\x125\n" +
	"\n" +
	"updated_by\x18\a \x01(\v2\x16.post.BaseUserResponseR\tupdatedBy\"s\n" +
	"\x10BaseUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x123\n" +
	"\aprofile\x18\x03 \x01(\v2\x19.post.BaseProfileResponseR\aprofile\"a\n" +
	"\x13BaseProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\"\x10\n" +
	"\x0eGetManyRequest\"c\n" +
	"\x12CreateTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slug\x88\x01\x01\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userIdB\a\n" +
	"\x05_slug\"!\n" +
	"\x0fCreatedResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x82\x06\n" +
	"\vPostService\x12>\n" +
	"\vCreateTopic\x12\x18.post.CreateTopicRequest\x1a\x15.post.CreatedResponse\x12D\n" +
	"\x11GetAllTopicsAdmin\x12\x14.post.GetManyRequest\x1a\x19.post.TopicsAdminResponse\x12>\n" +
	"\vUpdateTopic\x12\x18.post.UpdateTopicRequest\x1a\x15.post.UpdatedResponse\x12<\n" +
	"\vDeleteTopic\x12\x16.post.DeleteOneRequest\x1a\x15.post.DeletedResponse\x12>\n" +
	"\fDeleteTopics\x12\x17.post.DeleteManyRequest\x1a\x15.post.DeletedResponse\x12R\n" +
	"\x16PermanentlyDeleteTopic\x12!.post.PermanentlyDeleteOneRequest\x1a\x15.post.DeletedResponse\x12T\n" +
	"\x17PermanentlyDeleteTopics\x12\".post.PermanentlyDeleteManyRequest\x1a\x15.post.DeletedResponse\x12?\n" +
	"\fRestoreTopic\x12\x17.post.RestoreOneRequest\x1a\x16.post.RestoredResponse\x12A\n" +
	"\rRestoreTopics\x12\x18.post.RestoreManyRequest\x1a\x16.post.RestoredResponse\x12<\n" +
	"\n" +
	"CreatePost\x12\x17.post.CreatePostRequest\x1a\x15.post.CreatedResponse\x12C\n" +
	"\x10GetDeletedTopics\x12\x14.post.GetManyRequest\x1a\x19.post.TopicsAdminResponseB\x03Z\x01.b\x06proto3"

var (
	file_proto_post_proto_rawDescOnce sync.Once
	file_proto_post_proto_rawDescData []byte
)

func file_proto_post_proto_rawDescGZIP() []byte {
	file_proto_post_proto_rawDescOnce.Do(func() {
		file_proto_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_post_proto_rawDesc), len(file_proto_post_proto_rawDesc)))
	})
	return file_proto_post_proto_rawDescData
}

var file_proto_post_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_post_proto_goTypes = []any{
	(*CreatePostRequest)(nil),            // 0: post.CreatePostRequest
	(*CreateImageRequest)(nil),           // 1: post.CreateImageRequest
	(*RestoreManyRequest)(nil),           // 2: post.RestoreManyRequest
	(*RestoredResponse)(nil),             // 3: post.RestoredResponse
	(*RestoreOneRequest)(nil),            // 4: post.RestoreOneRequest
	(*PermanentlyDeleteManyRequest)(nil), // 5: post.PermanentlyDeleteManyRequest
	(*PermanentlyDeleteOneRequest)(nil),  // 6: post.PermanentlyDeleteOneRequest
	(*DeleteManyRequest)(nil),            // 7: post.DeleteManyRequest
	(*DeleteOneRequest)(nil),             // 8: post.DeleteOneRequest
	(*DeletedResponse)(nil),              // 9: post.DeletedResponse
	(*UpdatedResponse)(nil),              // 10: post.UpdatedResponse
	(*UpdateTopicRequest)(nil),           // 11: post.UpdateTopicRequest
	(*TopicsAdminResponse)(nil),          // 12: post.TopicsAdminResponse
	(*TopicAdminResponse)(nil),           // 13: post.TopicAdminResponse
	(*BaseUserResponse)(nil),             // 14: post.BaseUserResponse
	(*BaseProfileResponse)(nil),          // 15: post.BaseProfileResponse
	(*GetManyRequest)(nil),               // 16: post.GetManyRequest
	(*CreateTopicRequest)(nil),           // 17: post.CreateTopicRequest
	(*CreatedResponse)(nil),              // 18: post.CreatedResponse
}
var file_proto_post_proto_depIdxs = []int32{
	1,  // 0: post.CreatePostRequest.images:type_name -> post.CreateImageRequest
	13, // 1: post.TopicsAdminResponse.topics:type_name -> post.TopicAdminResponse
	14, // 2: post.TopicAdminResponse.created_by:type_name -> post.BaseUserResponse
	14, // 3: post.TopicAdminResponse.updated_by:type_name -> post.BaseUserResponse
	15, // 4: post.BaseUserResponse.profile:type_name -> post.BaseProfileResponse
	17, // 5: post.PostService.CreateTopic:input_type -> post.CreateTopicRequest
	16, // 6: post.PostService.GetAllTopicsAdmin:input_type -> post.GetManyRequest
	11, // 7: post.PostService.UpdateTopic:input_type -> post.UpdateTopicRequest
	8,  // 8: post.PostService.DeleteTopic:input_type -> post.DeleteOneRequest
	7,  // 9: post.PostService.DeleteTopics:input_type -> post.DeleteManyRequest
	6,  // 10: post.PostService.PermanentlyDeleteTopic:input_type -> post.PermanentlyDeleteOneRequest
	5,  // 11: post.PostService.PermanentlyDeleteTopics:input_type -> post.PermanentlyDeleteManyRequest
	4,  // 12: post.PostService.RestoreTopic:input_type -> post.RestoreOneRequest
	2,  // 13: post.PostService.RestoreTopics:input_type -> post.RestoreManyRequest
	0,  // 14: post.PostService.CreatePost:input_type -> post.CreatePostRequest
	16, // 15: post.PostService.GetDeletedTopics:input_type -> post.GetManyRequest
	18, // 16: post.PostService.CreateTopic:output_type -> post.CreatedResponse
	12, // 17: post.PostService.GetAllTopicsAdmin:output_type -> post.TopicsAdminResponse
	10, // 18: post.PostService.UpdateTopic:output_type -> post.UpdatedResponse
	9,  // 19: post.PostService.DeleteTopic:output_type -> post.DeletedResponse
	9,  // 20: post.PostService.DeleteTopics:output_type -> post.DeletedResponse
	9,  // 21: post.PostService.PermanentlyDeleteTopic:output_type -> post.DeletedResponse
	9,  // 22: post.PostService.PermanentlyDeleteTopics:output_type -> post.DeletedResponse
	3,  // 23: post.PostService.RestoreTopic:output_type -> post.RestoredResponse
	3,  // 24: post.PostService.RestoreTopics:output_type -> post.RestoredResponse
	18, // 25: post.PostService.CreatePost:output_type -> post.CreatedResponse
	12, // 26: post.PostService.GetDeletedTopics:output_type -> post.TopicsAdminResponse
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_post_proto_init() }
func file_proto_post_proto_init() {
	if File_proto_post_proto != nil {
		return
	}
	file_proto_post_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_post_proto_rawDesc), len(file_proto_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_post_proto_goTypes,
		DependencyIndexes: file_proto_post_proto_depIdxs,
		MessageInfos:      file_proto_post_proto_msgTypes,
	}.Build()
	File_proto_post_proto = out.File
	file_proto_post_proto_goTypes = nil
	file_proto_post_proto_depIdxs = nil
}
