// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: services/product/protobuf/product.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductsByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByCategoryRequest) Reset() {
	*x = GetProductsByCategoryRequest{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByCategoryRequest) ProtoMessage() {}

func (x *GetProductsByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetProductsByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductsByCategoryRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ProductsPublicResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Products      []*ProductPublicResponse `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsPublicResponse) Reset() {
	*x = ProductsPublicResponse{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsPublicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsPublicResponse) ProtoMessage() {}

func (x *ProductsPublicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsPublicResponse.ProtoReflect.Descriptor instead.
func (*ProductsPublicResponse) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductsPublicResponse) GetProducts() []*ProductPublicResponse {
	if x != nil {
		return x.Products
	}
	return nil
}

type CreateImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ColorId       string                 `protobuf:"bytes,2,opt,name=color_id,json=colorId,proto3" json:"color_id,omitempty"`
	File          []byte                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	IsThumbnail   bool                   `protobuf:"varint,5,opt,name=is_thumbnail,json=isThumbnail,proto3" json:"is_thumbnail,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateImageRequest) Reset() {
	*x = CreateImageRequest{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImageRequest) ProtoMessage() {}

func (x *CreateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImageRequest.ProtoReflect.Descriptor instead.
func (*CreateImageRequest) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{2}
}

func (x *CreateImageRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateImageRequest) GetColorId() string {
	if x != nil {
		return x.ColorId
	}
	return ""
}

func (x *CreateImageRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *CreateImageRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CreateImageRequest) GetIsThumbnail() bool {
	if x != nil {
		return x.IsThumbnail
	}
	return false
}

func (x *CreateImageRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CreateImageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateVariantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ColorId       string                 `protobuf:"bytes,3,opt,name=color_id,json=colorId,proto3" json:"color_id,omitempty"`
	SizeId        string                 `protobuf:"bytes,4,opt,name=size_id,json=sizeId,proto3" json:"size_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVariantRequest) Reset() {
	*x = CreateVariantRequest{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVariantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVariantRequest) ProtoMessage() {}

func (x *CreateVariantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVariantRequest.ProtoReflect.Descriptor instead.
func (*CreateVariantRequest) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{3}
}

func (x *CreateVariantRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateVariantRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateVariantRequest) GetColorId() string {
	if x != nil {
		return x.ColorId
	}
	return ""
}

func (x *CreateVariantRequest) GetSizeId() string {
	if x != nil {
		return x.SizeId
	}
	return ""
}

func (x *CreateVariantRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateVariantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateSizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSizeRequest) Reset() {
	*x = CreateSizeRequest{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSizeRequest) ProtoMessage() {}

func (x *CreateSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSizeRequest.ProtoReflect.Descriptor instead.
func (*CreateSizeRequest) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSizeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSizeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateColorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateColorRequest) Reset() {
	*x = CreateColorRequest{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColorRequest) ProtoMessage() {}

func (x *CreateColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColorRequest.ProtoReflect.Descriptor instead.
func (*CreateColorRequest) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{5}
}

func (x *CreateColorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateColorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedResponse) Reset() {
	*x = CreatedResponse{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedResponse) ProtoMessage() {}

func (x *CreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedResponse.ProtoReflect.Descriptor instead.
func (*CreatedResponse) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{6}
}

func (x *CreatedResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductBySlugRequest) Reset() {
	*x = GetProductBySlugRequest{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductBySlugRequest) ProtoMessage() {}

func (x *GetProductBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetProductBySlugRequest) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ProductPublicResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                  `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float32                 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	IsSale        *bool                   `protobuf:"varint,6,opt,name=is_sale,json=isSale,proto3,oneof" json:"is_sale,omitempty"`
	SalePrice     *float32                `protobuf:"fixed32,7,opt,name=sale_price,json=salePrice,proto3,oneof" json:"sale_price,omitempty"`
	StartSale     *string                 `protobuf:"bytes,8,opt,name=start_sale,json=startSale,proto3,oneof" json:"start_sale,omitempty"`
	EndSale       *string                 `protobuf:"bytes,9,opt,name=end_sale,json=endSale,proto3,oneof" json:"end_sale,omitempty"`
	Categories    []*BaseCategoryResponse `protobuf:"bytes,10,rep,name=categories,proto3" json:"categories,omitempty"`
	Variants      []*BaseVariantResponse  `protobuf:"bytes,11,rep,name=variants,proto3" json:"variants,omitempty"`
	Images        []*BaseImageResponse    `protobuf:"bytes,12,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductPublicResponse) Reset() {
	*x = ProductPublicResponse{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductPublicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPublicResponse) ProtoMessage() {}

func (x *ProductPublicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPublicResponse.ProtoReflect.Descriptor instead.
func (*ProductPublicResponse) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{8}
}

func (x *ProductPublicResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductPublicResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProductPublicResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProductPublicResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductPublicResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductPublicResponse) GetIsSale() bool {
	if x != nil && x.IsSale != nil {
		return *x.IsSale
	}
	return false
}

func (x *ProductPublicResponse) GetSalePrice() float32 {
	if x != nil && x.SalePrice != nil {
		return *x.SalePrice
	}
	return 0
}

func (x *ProductPublicResponse) GetStartSale() string {
	if x != nil && x.StartSale != nil {
		return *x.StartSale
	}
	return ""
}

func (x *ProductPublicResponse) GetEndSale() string {
	if x != nil && x.EndSale != nil {
		return *x.EndSale
	}
	return ""
}

func (x *ProductPublicResponse) GetCategories() []*BaseCategoryResponse {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ProductPublicResponse) GetVariants() []*BaseVariantResponse {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *ProductPublicResponse) GetImages() []*BaseImageResponse {
	if x != nil {
		return x.Images
	}
	return nil
}

type BaseImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Color         *BaseColorResponse     `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	IsThumbnail   bool                   `protobuf:"varint,5,opt,name=is_thumbnail,json=isThumbnail,proto3" json:"is_thumbnail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseImageResponse) Reset() {
	*x = BaseImageResponse{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseImageResponse) ProtoMessage() {}

func (x *BaseImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseImageResponse.ProtoReflect.Descriptor instead.
func (*BaseImageResponse) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{9}
}

func (x *BaseImageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseImageResponse) GetColor() *BaseColorResponse {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *BaseImageResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BaseImageResponse) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *BaseImageResponse) GetIsThumbnail() bool {
	if x != nil {
		return x.IsThumbnail
	}
	return false
}

type BaseColorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseColorResponse) Reset() {
	*x = BaseColorResponse{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseColorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseColorResponse) ProtoMessage() {}

func (x *BaseColorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseColorResponse.ProtoReflect.Descriptor instead.
func (*BaseColorResponse) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{10}
}

func (x *BaseColorResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseColorResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BaseSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSizeResponse) Reset() {
	*x = BaseSizeResponse{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSizeResponse) ProtoMessage() {}

func (x *BaseSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSizeResponse.ProtoReflect.Descriptor instead.
func (*BaseSizeResponse) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{11}
}

func (x *BaseSizeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseSizeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BaseInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SoldQuantity  int64                  `protobuf:"varint,2,opt,name=sold_quantity,json=soldQuantity,proto3" json:"sold_quantity,omitempty"`
	Stock         int64                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	IsStock       *bool                  `protobuf:"varint,4,opt,name=is_stock,json=isStock,proto3,oneof" json:"is_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseInventoryResponse) Reset() {
	*x = BaseInventoryResponse{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInventoryResponse) ProtoMessage() {}

func (x *BaseInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInventoryResponse.ProtoReflect.Descriptor instead.
func (*BaseInventoryResponse) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{12}
}

func (x *BaseInventoryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseInventoryResponse) GetSoldQuantity() int64 {
	if x != nil {
		return x.SoldQuantity
	}
	return 0
}

func (x *BaseInventoryResponse) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *BaseInventoryResponse) GetIsStock() bool {
	if x != nil && x.IsStock != nil {
		return *x.IsStock
	}
	return false
}

type BaseVariantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Color         *BaseColorResponse     `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Size          *BaseSizeResponse      `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Inventory     *BaseInventoryResponse `protobuf:"bytes,5,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseVariantResponse) Reset() {
	*x = BaseVariantResponse{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseVariantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseVariantResponse) ProtoMessage() {}

func (x *BaseVariantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseVariantResponse.ProtoReflect.Descriptor instead.
func (*BaseVariantResponse) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{13}
}

func (x *BaseVariantResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseVariantResponse) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *BaseVariantResponse) GetColor() *BaseColorResponse {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *BaseVariantResponse) GetSize() *BaseSizeResponse {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *BaseVariantResponse) GetInventory() *BaseInventoryResponse {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          *string                `protobuf:"bytes,2,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	ParentIds     []string               `protobuf:"bytes,3,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{14}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *CreateCategoryRequest) GetParentIds() []string {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

func (x *CreateCategoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	IsSale        bool                   `protobuf:"varint,4,opt,name=is_sale,json=isSale,proto3" json:"is_sale,omitempty"`
	SalePrice     *float32               `protobuf:"fixed32,5,opt,name=sale_price,json=salePrice,proto3,oneof" json:"sale_price,omitempty"`
	StartSale     *string                `protobuf:"bytes,6,opt,name=start_sale,json=startSale,proto3,oneof" json:"start_sale,omitempty"`
	EndSale       *string                `protobuf:"bytes,7,opt,name=end_sale,json=endSale,proto3,oneof" json:"end_sale,omitempty"`
	CategoryIds   []string               `protobuf:"bytes,8,rep,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	UserId        string                 `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{15}
}

func (x *CreateProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetIsSale() bool {
	if x != nil {
		return x.IsSale
	}
	return false
}

func (x *CreateProductRequest) GetSalePrice() float32 {
	if x != nil && x.SalePrice != nil {
		return *x.SalePrice
	}
	return 0
}

func (x *CreateProductRequest) GetStartSale() string {
	if x != nil && x.StartSale != nil {
		return *x.StartSale
	}
	return ""
}

func (x *CreateProductRequest) GetEndSale() string {
	if x != nil && x.EndSale != nil {
		return *x.EndSale
	}
	return ""
}

func (x *CreateProductRequest) GetCategoryIds() []string {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *CreateProductRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BaseCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseCategoryResponse) Reset() {
	*x = BaseCategoryResponse{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseCategoryResponse) ProtoMessage() {}

func (x *BaseCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseCategoryResponse.ProtoReflect.Descriptor instead.
func (*BaseCategoryResponse) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{16}
}

func (x *BaseCategoryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseCategoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseCategoryResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CategoryPublicResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                    `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Children      []*CategoryPublicResponse `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryPublicResponse) Reset() {
	*x = CategoryPublicResponse{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryPublicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryPublicResponse) ProtoMessage() {}

func (x *CategoryPublicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryPublicResponse.ProtoReflect.Descriptor instead.
func (*CategoryPublicResponse) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{17}
}

func (x *CategoryPublicResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CategoryPublicResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryPublicResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CategoryPublicResponse) GetChildren() []*CategoryPublicResponse {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetCategoryTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryTreeRequest) Reset() {
	*x = GetCategoryTreeRequest{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryTreeRequest) ProtoMessage() {}

func (x *GetCategoryTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryTreeRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryTreeRequest) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{18}
}

type CategoryTreeResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Categories    []*CategoryPublicResponse `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryTreeResponse) Reset() {
	*x = CategoryTreeResponse{}
	mi := &file_services_product_protobuf_product_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryTreeResponse) ProtoMessage() {}

func (x *CategoryTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_protobuf_product_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryTreeResponse.ProtoReflect.Descriptor instead.
func (*CategoryTreeResponse) Descriptor() ([]byte, []int) {
	return file_services_product_protobuf_product_proto_rawDescGZIP(), []int{19}
}

func (x *CategoryTreeResponse) GetCategories() []*CategoryPublicResponse {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_services_product_protobuf_product_proto protoreflect.FileDescriptor

const file_services_product_protobuf_product_proto_rawDesc = "" +
	"\n" +
	"'services/product/protobuf/product.proto\x12\aproduct\"2\n" +
	"\x1cGetProductsByCategoryRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"T\n" +
	"\x16ProductsPublicResponse\x12:\n" +
	"\bproducts\x18\x01 \x03(\v2\x1e.product.ProductPublicResponseR\bproducts\"\xda\x01\n" +
	"\x12CreateImageRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\bcolor_id\x18\x02 \x01(\tR\acolorId\x12\x12\n" +
	"\x04file\x18\x03 \x01(\fR\x04file\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12!\n" +
	"\fis_thumbnail\x18\x05 \x01(\bR\visThumbnail\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\"\xb0\x01\n" +
	"\x14CreateVariantRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x19\n" +
	"\bcolor_id\x18\x03 \x01(\tR\acolorId\x12\x17\n" +
	"\asize_id\x18\x04 \x01(\tR\x06sizeId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\"@\n" +
	"\x11CreateSizeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"A\n" +
	"\x12CreateColorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"!\n" +
	"\x0fCreatedResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x17GetProductBySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\xf3\x03\n" +
	"\x15ProductPublicResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12\x1c\n" +
	"\ais_sale\x18\x06 \x01(\bH\x00R\x06isSale\x88\x01\x01\x12\"\n" +
	"\n" +
	"sale_price\x18\a \x01(\x02H\x01R\tsalePrice\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_sale\x18\b \x01(\tH\x02R\tstartSale\x88\x01\x01\x12\x1e\n" +
	"\bend_sale\x18\t \x01(\tH\x03R\aendSale\x88\x01\x01\x12=\n" +
	"\n" +
	"categories\x18\n" +
	" \x03(\v2\x1d.product.BaseCategoryResponseR\n" +
	"categories\x128\n" +
	"\bvariants\x18\v \x03(\v2\x1c.product.BaseVariantResponseR\bvariants\x122\n" +
	"\x06images\x18\f \x03(\v2\x1a.product.BaseImageResponseR\x06imagesB\n" +
	"\n" +
	"\b_is_saleB\r\n" +
	"\v_sale_priceB\r\n" +
	"\v_start_saleB\v\n" +
	"\t_end_sale\"\xa9\x01\n" +
	"\x11BaseImageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x05color\x18\x02 \x01(\v2\x1a.product.BaseColorResponseR\x05color\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\x12!\n" +
	"\fis_thumbnail\x18\x05 \x01(\bR\visThumbnail\"7\n" +
	"\x11BaseColorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"6\n" +
	"\x10BaseSizeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8f\x01\n" +
	"\x15BaseInventoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rsold_quantity\x18\x02 \x01(\x03R\fsoldQuantity\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x03R\x05stock\x12\x1e\n" +
	"\bis_stock\x18\x04 \x01(\bH\x00R\aisStock\x88\x01\x01B\v\n" +
	"\t_is_stock\"\xd6\x01\n" +
	"\x13BaseVariantResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x120\n" +
	"\x05color\x18\x03 \x01(\v2\x1a.product.BaseColorResponseR\x05color\x12-\n" +
	"\x04size\x18\x04 \x01(\v2\x19.product.BaseSizeResponseR\x04size\x12<\n" +
	"\tinventory\x18\x05 \x01(\v2\x1e.product.BaseInventoryResponseR\tinventory\"\x85\x01\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slug\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x03 \x03(\tR\tparentIds\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userIdB\a\n" +
	"\x05_slug\"\xcc\x02\n" +
	"\x14CreateProductRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x17\n" +
	"\ais_sale\x18\x04 \x01(\bR\x06isSale\x12\"\n" +
	"\n" +
	"sale_price\x18\x05 \x01(\x02H\x00R\tsalePrice\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_sale\x18\x06 \x01(\tH\x01R\tstartSale\x88\x01\x01\x12\x1e\n" +
	"\bend_sale\x18\a \x01(\tH\x02R\aendSale\x88\x01\x01\x12!\n" +
	"\fcategory_ids\x18\b \x03(\tR\vcategoryIds\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userIdB\r\n" +
	"\v_sale_priceB\r\n" +
	"\v_start_saleB\v\n" +
	"\t_end_sale\"N\n" +
	"\x14BaseCategoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\"\x8d\x01\n" +
	"\x16CategoryPublicResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12;\n" +
	"\bchildren\x18\x04 \x03(\v2\x1f.product.CategoryPublicResponseR\bchildren\"\x18\n" +
	"\x16GetCategoryTreeRequest\"W\n" +
	"\x14CategoryTreeResponse\x12?\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1f.product.CategoryPublicResponseR\n" +
	"categories2\xca\x05\n" +
	"\x0eProductService\x12J\n" +
	"\x0eCreateCategory\x12\x1e.product.CreateCategoryRequest\x1a\x18.product.CreatedResponse\x12Q\n" +
	"\x0fGetCategoryTree\x12\x1f.product.GetCategoryTreeRequest\x1a\x1d.product.CategoryTreeResponse\x12H\n" +
	"\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x18.product.CreatedResponse\x12T\n" +
	"\x10GetProductBySlug\x12 .product.GetProductBySlugRequest\x1a\x1e.product.ProductPublicResponse\x12D\n" +
	"\vCreateColor\x12\x1b.product.CreateColorRequest\x1a\x18.product.CreatedResponse\x12B\n" +
	"\n" +
	"CreateSize\x12\x1a.product.CreateSizeRequest\x1a\x18.product.CreatedResponse\x12H\n" +
	"\rCreateVariant\x12\x1d.product.CreateVariantRequest\x1a\x18.product.CreatedResponse\x12D\n" +
	"\vCreateImage\x12\x1b.product.CreateImageRequest\x1a\x18.product.CreatedResponse\x12_\n" +
	"\x15GetProductsByCategory\x12%.product.GetProductsByCategoryRequest\x1a\x1f.product.ProductsPublicResponseBAZ?github.com/SomeHowMicroservice/shm-be/services/product/protobufb\x06proto3"

var (
	file_services_product_protobuf_product_proto_rawDescOnce sync.Once
	file_services_product_protobuf_product_proto_rawDescData []byte
)

func file_services_product_protobuf_product_proto_rawDescGZIP() []byte {
	file_services_product_protobuf_product_proto_rawDescOnce.Do(func() {
		file_services_product_protobuf_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_product_protobuf_product_proto_rawDesc), len(file_services_product_protobuf_product_proto_rawDesc)))
	})
	return file_services_product_protobuf_product_proto_rawDescData
}

var file_services_product_protobuf_product_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_services_product_protobuf_product_proto_goTypes = []any{
	(*GetProductsByCategoryRequest)(nil), // 0: product.GetProductsByCategoryRequest
	(*ProductsPublicResponse)(nil),       // 1: product.ProductsPublicResponse
	(*CreateImageRequest)(nil),           // 2: product.CreateImageRequest
	(*CreateVariantRequest)(nil),         // 3: product.CreateVariantRequest
	(*CreateSizeRequest)(nil),            // 4: product.CreateSizeRequest
	(*CreateColorRequest)(nil),           // 5: product.CreateColorRequest
	(*CreatedResponse)(nil),              // 6: product.CreatedResponse
	(*GetProductBySlugRequest)(nil),      // 7: product.GetProductBySlugRequest
	(*ProductPublicResponse)(nil),        // 8: product.ProductPublicResponse
	(*BaseImageResponse)(nil),            // 9: product.BaseImageResponse
	(*BaseColorResponse)(nil),            // 10: product.BaseColorResponse
	(*BaseSizeResponse)(nil),             // 11: product.BaseSizeResponse
	(*BaseInventoryResponse)(nil),        // 12: product.BaseInventoryResponse
	(*BaseVariantResponse)(nil),          // 13: product.BaseVariantResponse
	(*CreateCategoryRequest)(nil),        // 14: product.CreateCategoryRequest
	(*CreateProductRequest)(nil),         // 15: product.CreateProductRequest
	(*BaseCategoryResponse)(nil),         // 16: product.BaseCategoryResponse
	(*CategoryPublicResponse)(nil),       // 17: product.CategoryPublicResponse
	(*GetCategoryTreeRequest)(nil),       // 18: product.GetCategoryTreeRequest
	(*CategoryTreeResponse)(nil),         // 19: product.CategoryTreeResponse
}
var file_services_product_protobuf_product_proto_depIdxs = []int32{
	8,  // 0: product.ProductsPublicResponse.products:type_name -> product.ProductPublicResponse
	16, // 1: product.ProductPublicResponse.categories:type_name -> product.BaseCategoryResponse
	13, // 2: product.ProductPublicResponse.variants:type_name -> product.BaseVariantResponse
	9,  // 3: product.ProductPublicResponse.images:type_name -> product.BaseImageResponse
	10, // 4: product.BaseImageResponse.color:type_name -> product.BaseColorResponse
	10, // 5: product.BaseVariantResponse.color:type_name -> product.BaseColorResponse
	11, // 6: product.BaseVariantResponse.size:type_name -> product.BaseSizeResponse
	12, // 7: product.BaseVariantResponse.inventory:type_name -> product.BaseInventoryResponse
	17, // 8: product.CategoryPublicResponse.children:type_name -> product.CategoryPublicResponse
	17, // 9: product.CategoryTreeResponse.categories:type_name -> product.CategoryPublicResponse
	14, // 10: product.ProductService.CreateCategory:input_type -> product.CreateCategoryRequest
	18, // 11: product.ProductService.GetCategoryTree:input_type -> product.GetCategoryTreeRequest
	15, // 12: product.ProductService.CreateProduct:input_type -> product.CreateProductRequest
	7,  // 13: product.ProductService.GetProductBySlug:input_type -> product.GetProductBySlugRequest
	5,  // 14: product.ProductService.CreateColor:input_type -> product.CreateColorRequest
	4,  // 15: product.ProductService.CreateSize:input_type -> product.CreateSizeRequest
	3,  // 16: product.ProductService.CreateVariant:input_type -> product.CreateVariantRequest
	2,  // 17: product.ProductService.CreateImage:input_type -> product.CreateImageRequest
	0,  // 18: product.ProductService.GetProductsByCategory:input_type -> product.GetProductsByCategoryRequest
	6,  // 19: product.ProductService.CreateCategory:output_type -> product.CreatedResponse
	19, // 20: product.ProductService.GetCategoryTree:output_type -> product.CategoryTreeResponse
	6,  // 21: product.ProductService.CreateProduct:output_type -> product.CreatedResponse
	8,  // 22: product.ProductService.GetProductBySlug:output_type -> product.ProductPublicResponse
	6,  // 23: product.ProductService.CreateColor:output_type -> product.CreatedResponse
	6,  // 24: product.ProductService.CreateSize:output_type -> product.CreatedResponse
	6,  // 25: product.ProductService.CreateVariant:output_type -> product.CreatedResponse
	6,  // 26: product.ProductService.CreateImage:output_type -> product.CreatedResponse
	1,  // 27: product.ProductService.GetProductsByCategory:output_type -> product.ProductsPublicResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_services_product_protobuf_product_proto_init() }
func file_services_product_protobuf_product_proto_init() {
	if File_services_product_protobuf_product_proto != nil {
		return
	}
	file_services_product_protobuf_product_proto_msgTypes[8].OneofWrappers = []any{}
	file_services_product_protobuf_product_proto_msgTypes[12].OneofWrappers = []any{}
	file_services_product_protobuf_product_proto_msgTypes[14].OneofWrappers = []any{}
	file_services_product_protobuf_product_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_product_protobuf_product_proto_rawDesc), len(file_services_product_protobuf_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_product_protobuf_product_proto_goTypes,
		DependencyIndexes: file_services_product_protobuf_product_proto_depIdxs,
		MessageInfos:      file_services_product_protobuf_product_proto_msgTypes,
	}.Build()
	File_services_product_protobuf_product_proto = out.File
	file_services_product_protobuf_product_proto_goTypes = nil
	file_services_product_protobuf_product_proto_depIdxs = nil
}
