// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: services/auth/protobuf/auth.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_protobuf_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ChangePasswordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_protobuf_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RefreshTokenRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type RefreshTokenResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessExpiresIn  int64                  `protobuf:"varint,2,opt,name=access_expires_in,json=accessExpiresIn,proto3" json:"access_expires_in,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RefreshExpiresIn int64                  `protobuf:"varint,4,opt,name=refresh_expires_in,json=refreshExpiresIn,proto3" json:"refresh_expires_in,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_protobuf_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetAccessExpiresIn() int64 {
	if x != nil {
		return x.AccessExpiresIn
	}
	return 0
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshExpiresIn() int64 {
	if x != nil {
		return x.RefreshExpiresIn
	}
	return 0
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_protobuf_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_protobuf_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SignUpRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignUpResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RegistrationToken string                 `protobuf:"bytes,1,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_protobuf_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SignUpResponse) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

type VerifySignUpRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RegistrationToken string                 `protobuf:"bytes,1,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"`
	Otp               string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifySignUpRequest) Reset() {
	*x = VerifySignUpRequest{}
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySignUpRequest) ProtoMessage() {}

func (x *VerifySignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySignUpRequest.ProtoReflect.Descriptor instead.
func (*VerifySignUpRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_protobuf_auth_proto_rawDescGZIP(), []int{6}
}

func (x *VerifySignUpRequest) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

func (x *VerifySignUpRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type SignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_protobuf_auth_proto_rawDescGZIP(), []int{7}
}

func (x *SignInRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoggedInResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessExpiresIn  int64                  `protobuf:"varint,2,opt,name=access_expires_in,json=accessExpiresIn,proto3" json:"access_expires_in,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RefreshExpiresIn int64                  `protobuf:"varint,4,opt,name=refresh_expires_in,json=refreshExpiresIn,proto3" json:"refresh_expires_in,omitempty"`
	User             *AuthResponse          `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoggedInResponse) Reset() {
	*x = LoggedInResponse{}
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggedInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggedInResponse) ProtoMessage() {}

func (x *LoggedInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_protobuf_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggedInResponse.ProtoReflect.Descriptor instead.
func (*LoggedInResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_protobuf_auth_proto_rawDescGZIP(), []int{8}
}

func (x *LoggedInResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoggedInResponse) GetAccessExpiresIn() int64 {
	if x != nil {
		return x.AccessExpiresIn
	}
	return 0
}

func (x *LoggedInResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoggedInResponse) GetRefreshExpiresIn() int64 {
	if x != nil {
		return x.RefreshExpiresIn
	}
	return 0
}

func (x *LoggedInResponse) GetUser() *AuthResponse {
	if x != nil {
		return x.User
	}
	return nil
}

var File_services_auth_protobuf_auth_proto protoreflect.FileDescriptor

const file_services_auth_protobuf_auth_proto_rawDesc = "" +
	"\n" +
	"!services/auth/protobuf/auth.proto\x12\x04auth\"m\n" +
	"\x15ChangePasswordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\";\n" +
	"\x13RefreshTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\"\xb8\x01\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12*\n" +
	"\x11access_expires_in\x18\x02 \x01(\x03R\x0faccessExpiresIn\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12,\n" +
	"\x12refresh_expires_in\x18\x04 \x01(\x03R\x10refreshExpiresIn\"o\n" +
	"\fAuthResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"]\n" +
	"\rSignUpRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"?\n" +
	"\x0eSignUpResponse\x12-\n" +
	"\x12registration_token\x18\x01 \x01(\tR\x11registrationToken\"V\n" +
	"\x13VerifySignUpRequest\x12-\n" +
	"\x12registration_token\x18\x01 \x01(\tR\x11registrationToken\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"G\n" +
	"\rSignInRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xdc\x01\n" +
	"\x10LoggedInResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12*\n" +
	"\x11access_expires_in\x18\x02 \x01(\x03R\x0faccessExpiresIn\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12,\n" +
	"\x12refresh_expires_in\x18\x04 \x01(\x03R\x10refreshExpiresIn\x12&\n" +
	"\x04user\x18\x05 \x01(\v2\x12.auth.AuthResponseR\x04user2\xce\x02\n" +
	"\vAuthService\x123\n" +
	"\x06SignUp\x12\x13.auth.SignUpRequest\x1a\x14.auth.SignUpResponse\x12A\n" +
	"\fVerifySignUp\x12\x19.auth.VerifySignUpRequest\x1a\x16.auth.LoggedInResponse\x125\n" +
	"\x06SignIn\x12\x13.auth.SignInRequest\x1a\x16.auth.LoggedInResponse\x12E\n" +
	"\fRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x1a.auth.RefreshTokenResponse\x12I\n" +
	"\x0eChangePassword\x12\x1b.auth.ChangePasswordRequest\x1a\x1a.auth.RefreshTokenResponseB>Z<github.com/SomeHowMicroservice/shm-be/services/auth/protobufb\x06proto3"

var (
	file_services_auth_protobuf_auth_proto_rawDescOnce sync.Once
	file_services_auth_protobuf_auth_proto_rawDescData []byte
)

func file_services_auth_protobuf_auth_proto_rawDescGZIP() []byte {
	file_services_auth_protobuf_auth_proto_rawDescOnce.Do(func() {
		file_services_auth_protobuf_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_auth_protobuf_auth_proto_rawDesc), len(file_services_auth_protobuf_auth_proto_rawDesc)))
	})
	return file_services_auth_protobuf_auth_proto_rawDescData
}

var file_services_auth_protobuf_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_services_auth_protobuf_auth_proto_goTypes = []any{
	(*ChangePasswordRequest)(nil), // 0: auth.ChangePasswordRequest
	(*RefreshTokenRequest)(nil),   // 1: auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),  // 2: auth.RefreshTokenResponse
	(*AuthResponse)(nil),          // 3: auth.AuthResponse
	(*SignUpRequest)(nil),         // 4: auth.SignUpRequest
	(*SignUpResponse)(nil),        // 5: auth.SignUpResponse
	(*VerifySignUpRequest)(nil),   // 6: auth.VerifySignUpRequest
	(*SignInRequest)(nil),         // 7: auth.SignInRequest
	(*LoggedInResponse)(nil),      // 8: auth.LoggedInResponse
}
var file_services_auth_protobuf_auth_proto_depIdxs = []int32{
	3, // 0: auth.LoggedInResponse.user:type_name -> auth.AuthResponse
	4, // 1: auth.AuthService.SignUp:input_type -> auth.SignUpRequest
	6, // 2: auth.AuthService.VerifySignUp:input_type -> auth.VerifySignUpRequest
	7, // 3: auth.AuthService.SignIn:input_type -> auth.SignInRequest
	1, // 4: auth.AuthService.RefreshToken:input_type -> auth.RefreshTokenRequest
	0, // 5: auth.AuthService.ChangePassword:input_type -> auth.ChangePasswordRequest
	5, // 6: auth.AuthService.SignUp:output_type -> auth.SignUpResponse
	8, // 7: auth.AuthService.VerifySignUp:output_type -> auth.LoggedInResponse
	8, // 8: auth.AuthService.SignIn:output_type -> auth.LoggedInResponse
	2, // 9: auth.AuthService.RefreshToken:output_type -> auth.RefreshTokenResponse
	2, // 10: auth.AuthService.ChangePassword:output_type -> auth.RefreshTokenResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_auth_protobuf_auth_proto_init() }
func file_services_auth_protobuf_auth_proto_init() {
	if File_services_auth_protobuf_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_auth_protobuf_auth_proto_rawDesc), len(file_services_auth_protobuf_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_auth_protobuf_auth_proto_goTypes,
		DependencyIndexes: file_services_auth_protobuf_auth_proto_depIdxs,
		MessageInfos:      file_services_auth_protobuf_auth_proto_msgTypes,
	}.Build()
	File_services_auth_protobuf_auth_proto = out.File
	file_services_auth_protobuf_auth_proto_goTypes = nil
	file_services_auth_protobuf_auth_proto_depIdxs = nil
}
